name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered?

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - New Tracker Support
        - New Parser/Format
        - CLI Improvement
        - Performance
        - Developer Experience
        - Documentation
        - Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (your opinion)
      options:
        - Nice to have
        - Would be helpful
        - Important for my workflow
        - Critical blocker

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples

